name = "crafthead-dev"
main = "worker/index.ts"
workers_dev = true
compatibility_date = "2024-01-28"
analytics_engine_datasets = [
	{ binding = "CRAFTHEAD_ANALYTICS" }
]

compatibility_flags = ["nodejs_compat", "no_nodejs_compat_v2"]

[site]
bucket = "./website"

[build]
command = "npm run build" # required

[env.production]
name = "crafthead"
route = { pattern = "crafthead.net/*", zone_name = "crafthead.net" }
analytics_engine_datasets = [
	{ binding = "CRAFTHEAD_ANALYTICS" }
]
services = [
  { binding = "PLAYERDB", service = "playerdb" }
]
