name: Test
on: [pull_request]

jobs:
  test-node:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node: [20, 22]
    name: Node ${{ matrix.node }} Test
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - uses: dtolnay/rust-toolchain@stable
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: latest
      - uses: Swatinem/rust-cache@v2

      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm run test
